//
// Created by roman on 1.5.2017.
//

#ifndef PV264_PROJECT_RENDERINGLAYER_BACKGROUND_H
#define PV264_PROJECT_RENDERINGLAYER_BACKGROUND_H

struct RenderingLayer_Background{

};
#endif //PV264_PROJECT_RENDERINGLAYER_BACKGROUND_H
