//
// Created by roman on 29.4.2017.
//

#ifndef PV264_PROJECT_CLIENTMENUINPUTHOLDER_H
#define PV264_PROJECT_CLIENTMENUINPUTHOLDER_H

struct ClientMenuInputHolder{

};
#endif //PV264_PROJECT_CLIENTMENUINPUTHOLDER_H
